version: "3.7"
services:
  pozos-website:
    image:  php:apache
    volumes:
      - ./website:/var/www/html
    environment:
      USERNAME: "toto"
      PASSWORD: "python"
    networks:
      - pozos
    ports:
      - 8002:80
    depends_on:
      - pozos-api

  pozos-api:
    platform: linux/arm64/v8
    build: 
      context: .
      dockerfile: ./simple_api/Dockerfile
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
      - $HOME/.aws:/root/.aws
    ports:
      - 4000:5000
    networks:
      - pozos

networks:
  pozos:
    name: pozos
